const PUERTO = 8080;

const METODO_EFECTIVO = "efectivo";
const METODO_TARJETA_CREDITO = "TC";
const METODOS_FORMA_PAGO = {METODO_EFECTIVO, METODO_TARJETA_CREDITO}

const MODELO_CIUDADES = "Ciudades";
const MODELO_PEDIDO = "PedidosLoQueSea";
const MODELOS_BD = {MODELO_CIUDADES, MODELO_PEDIDO}


const CONSTANTES = {
    PUERTO,
    METODOS_FORMA_PAGO,
    MODELOS_BD
};

export default CONSTANTES;
